services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: sales_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "7878:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:

